version: "3.9"
name: auth_service
networks:
  auth_service:

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=auth_service
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    networks:
      - auth_service

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - auth_service

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - DB_SOURCE=postgresql://root:12345678@postgres:5432/auth_service?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - auth_service

volumes:
  data-volume:
