version: "3.9"
name: mb-backend
networks:
  mb-backend:

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=mb_backend
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    networks:
      - mb-backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mb-backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - DB_SOURCE=postgresql://root:12345678@postgres:5432/mb_backend?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - mb-backend
      
volumes:
  data-volume:
