// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              int64              `json:"id"`
	AccountID       uuid.UUID          `json:"account_id"`
	Email           string             `json:"email"`
	HashPassword    string             `json:"hash_password"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	IsEmailVerified bool               `json:"is_email_verified"`
}

type Device struct {
	ID             int64              `json:"id"`
	DeviceID       string             `json:"device_id"`
	AccountID      uuid.UUID          `json:"account_id"`
	ExpTokenDevice time.Time          `json:"exp_token_device"`
	CreatedAt      time.Time          `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Profile struct {
	ID          int64              `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	PhoneNumber string             `json:"phone_number"`
	Address     pgtype.Text        `json:"address"`
	Birthday    time.Time          `json:"birthday"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Session struct {
	ID           int64     `json:"id"`
	AccountID    uuid.UUID `json:"account_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientID     string    `json:"client_id"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiredAt    time.Time `json:"expired_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	AccountID  uuid.UUID `json:"account_id"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
