// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ChangePassword(ctx context.Context, arg ChangePasswordParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteAccount(ctx context.Context, accountID uuid.UUID) error
	DeleteProfile(ctx context.Context, accountID uuid.UUID) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAllDevices(ctx context.Context, accountID uuid.UUID) ([]Device, error)
	GetOneDevice(ctx context.Context, arg GetOneDeviceParams) (Device, error)
	GetOneProfile(ctx context.Context, accountID uuid.UUID) (Profile, error)
	GetOneSession(ctx context.Context, refreshToken string) (Session, error)
	GetProfileAccount(ctx context.Context, email string) (GetProfileAccountRow, error)
	GetVerifyEmailBySecretCode(ctx context.Context, arg GetVerifyEmailBySecretCodeParams) (VerifyEmail, error)
	UpdateAccountEmail(ctx context.Context, accountID uuid.UUID) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) error
}

var _ Querier = (*Queries)(nil)
